# Server
server.port=${PORT:8080}
spring.application.name=flyte

# Database
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=MiUlAHQwQqzaJPekVxSZLmcBrvEDEGDu
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Stripe
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.public.key=${STRIPE_PUBLIC_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:test}

# Mpesa
mpesa.consumer.key=${MPESA_CONSUMER_KEY}
mpesa.consumer.secret=${MPESA_CONSUMER_SECRET}
mpesa.shortcode=${MPESA_SHORTCODE:174379}
mpesa.passkey=${MPESA_PASSKEY}
mpesa.callback.url=${MPESA_CALLBACK_URL}

# Admin
flyte.admin.username=${FLYTE_ADMIN_USERNAME:admin}
flyte.admin.email=${FLYTE_ADMIN_EMAIL:admin@flyte.local}
flyte.admin.password=${FLYTE_ADMIN_PASSWORD:password123}

# Logging
logging.level.com.flyte=DEBUG
logging.level.org.springframework.security=INFO
server.error.include-message=always