spring.application.name=Flyte

# SQLite Datasource
spring.datasource.url=jdbc:sqlite:flyte_booking.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=false

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=8080
